// <auto-generated />
namespace Vektorel.EMarket.Datacore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class moduleroute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moduleroute));
        
        string IMigrationMetadata.Id
        {
            get { return "201902232139191_moduleroute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
